# Generated by Django 5.2 on 2025-07-02 20:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneratedContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AnualPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unit_title", models.JSONField(default=list)),
                ("goals", models.JSONField(default=list)),
                ("unit_contents", models.JSONField(default=list)),
                ("methodologies", models.JSONField(default=list)),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True, null=True, upload_to="annualplan_pdf/"
                    ),
                ),
                ("start_date", models.DateField(default=django.utils.timezone.now)),
                ("end_date", models.DateField(default=django.utils.timezone.now)),
                ("year", models.PositiveIntegerField(default=2025)),
                ("grade", models.CharField(default="Primero", max_length=200)),
                ("evaluation_criteria", models.JSONField(default=list)),
                ("evaluation_indicators", models.JSONField(default=list)),
                (
                    "teacher_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "college_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("area", models.CharField(blank=True, max_length=200, null=True)),
                ("parallel", models.CharField(blank=True, max_length=200, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "generatedContentId",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_annualplans",
                        to="educamy.generatedcontent",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MicroPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unit_title", models.JSONField(default=list)),
                ("goals", models.JSONField(default=list)),
                ("topic", models.JSONField(default=list)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("grade", models.CharField(max_length=200)),
                (
                    "pdf_file",
                    models.FileField(blank=True, null=True, upload_to="microplan_pdf/"),
                ),
                ("generated_content", models.TextField()),
                ("year", models.PositiveIntegerField(default=2025)),
                ("content", models.TextField()),
                ("evaluation_criteria", models.JSONField(default=list)),
                ("evaluation_indicators", models.JSONField(default=list)),
                (
                    "teacher_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "college_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("area", models.CharField(blank=True, max_length=200, null=True)),
                ("parallel", models.CharField(blank=True, max_length=200, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "generatedContentId",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_microplans",
                        to="educamy.generatedcontent",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PptxFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pptxfile",
                    models.FileField(blank=True, null=True, upload_to="pptx_files/"),
                ),
                ("title", models.CharField(blank=True, max_length=200, null=True)),
                ("date", models.DateField()),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "anual_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pptx_files",
                        to="educamy.anualplan",
                    ),
                ),
                (
                    "micro_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pptx_files",
                        to="educamy.microplan",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="user_photos/"),
                ),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
                ("last_name", models.CharField(blank=True, max_length=200, null=True)),
                ("email", models.EmailField(blank=True, max_length=200, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content_topic", models.TextField()),
                ("unit_number", models.IntegerField()),
                ("quiz_data", models.TextField()),
                (
                    "pdf_file",
                    models.FileField(blank=True, null=True, upload_to="quizzes/"),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Borrador"),
                            ("published", "Publicado"),
                            ("completed", "Completado"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "anual_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quizzes_anual",
                        to="educamy.anualplan",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "microplan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quizzes_micro",
                        to="educamy.microplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quiz",
                "verbose_name_plural": "Quizzes",
                "ordering": ["-created_date"],
            },
        ),
        migrations.CreateModel(
            name="SchoolSubject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="school_subject_files/"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="school_subjects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="microplan",
            name="school_subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="educamy.schoolsubject",
            ),
        ),
        migrations.AddField(
            model_name="generatedcontent",
            name="school_subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="educamy.schoolsubject"
            ),
        ),
        migrations.AddField(
            model_name="anualplan",
            name="school_subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="educamy.schoolsubject",
            ),
        ),
    ]
