# Generated by Django 5.2 on 2025-06-23 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educamy', '0018_anualplan_parallel_microplan_parallel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anualplan',
            name='transversal_value',
        ),
        migrations.RemoveField(
            model_name='microplan',
            name='transversal_value',
        ),
    ]
